package Util;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;


public class Util {

    
    /**
     * Academic Integrity Statement: the Method encodeWithMD5() is auto-generated by Chat-GPT.
     * @param input String that is pending to be encrypted.
     * @return Encrypted MD5 String
     */
    public static String encodeWithMD5(String input) {
        try {
            // Create a MessageDigest instance for MD5
            MessageDigest md = MessageDigest.getInstance("MD5");

            // Add the input bytes to the digest
            md.update(input.getBytes());

            // Get the hash bytes
            byte[] digest = md.digest();
            
            // Convert the hash bytes to a hexadecimal format
            StringBuilder hexString = new StringBuilder();
            for (byte b : digest) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            // Return the resulting hexadecimal string
            return hexString.toString();

        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }
    
    public static int[] pageHelper(int total){
        return new int[1];
    }



}
